# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/preferences.ui'
#
# Created: Fri Sep 13 18:19:42 2013
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Preferences(object):
    def setupUi(self, Preferences):
        Preferences.setObjectName("Preferences")
        Preferences.resize(405, 450)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Preferences)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtGui.QTabWidget(Preferences)
        self.tabWidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtGui.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_1)
        self.verticalLayout.setSpacing(12)
        self.verticalLayout.setObjectName("verticalLayout")
        self.showEstimates = QtGui.QCheckBox(self.tab_1)
        self.showEstimates.setObjectName("showEstimates")
        self.verticalLayout.addWidget(self.showEstimates)
        self.showProgress = QtGui.QCheckBox(self.tab_1)
        self.showProgress.setObjectName("showProgress")
        self.verticalLayout.addWidget(self.showProgress)
        self.stripHTML = QtGui.QCheckBox(self.tab_1)
        self.stripHTML.setObjectName("stripHTML")
        self.verticalLayout.addWidget(self.stripHTML)
        self.pastePNG = QtGui.QCheckBox(self.tab_1)
        self.pastePNG.setObjectName("pastePNG")
        self.verticalLayout.addWidget(self.pastePNG)
        self.useCurrent = QtGui.QComboBox(self.tab_1)
        self.useCurrent.setObjectName("useCurrent")
        self.useCurrent.addItem("")
        self.useCurrent.addItem("")
        self.verticalLayout.addWidget(self.useCurrent)
        self.newSpread = QtGui.QComboBox(self.tab_1)
        self.newSpread.setObjectName("newSpread")
        self.verticalLayout.addWidget(self.newSpread)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_23 = QtGui.QLabel(self.tab_1)
        self.label_23.setObjectName("label_23")
        self.gridLayout_4.addWidget(self.label_23, 0, 0, 1, 1)
        self.dayOffset = QtGui.QSpinBox(self.tab_1)
        self.dayOffset.setMaximumSize(QtCore.QSize(60, 16777215))
        self.dayOffset.setMaximum(23)
        self.dayOffset.setObjectName("dayOffset")
        self.gridLayout_4.addWidget(self.dayOffset, 0, 1, 1, 1)
        self.label_24 = QtGui.QLabel(self.tab_1)
        self.label_24.setObjectName("label_24")
        self.gridLayout_4.addWidget(self.label_24, 1, 0, 1, 1)
        self.lrnCutoff = QtGui.QSpinBox(self.tab_1)
        self.lrnCutoff.setMaximumSize(QtCore.QSize(60, 16777215))
        self.lrnCutoff.setMaximum(999)
        self.lrnCutoff.setObjectName("lrnCutoff")
        self.gridLayout_4.addWidget(self.lrnCutoff, 1, 1, 1, 1)
        self.label_29 = QtGui.QLabel(self.tab_1)
        self.label_29.setObjectName("label_29")
        self.gridLayout_4.addWidget(self.label_29, 1, 2, 1, 1)
        self.label_30 = QtGui.QLabel(self.tab_1)
        self.label_30.setObjectName("label_30")
        self.gridLayout_4.addWidget(self.label_30, 2, 0, 1, 1)
        self.timeLimit = QtGui.QSpinBox(self.tab_1)
        self.timeLimit.setMaximum(9999)
        self.timeLimit.setObjectName("timeLimit")
        self.gridLayout_4.addWidget(self.timeLimit, 2, 1, 1, 1)
        self.label_39 = QtGui.QLabel(self.tab_1)
        self.label_39.setObjectName("label_39")
        self.gridLayout_4.addWidget(self.label_39, 2, 2, 1, 1)
        self.label_40 = QtGui.QLabel(self.tab_1)
        self.label_40.setObjectName("label_40")
        self.gridLayout_4.addWidget(self.label_40, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_4)
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem)
        self.profilePass = QtGui.QPushButton(self.tab_1)
        self.profilePass.setAutoDefault(False)
        self.profilePass.setObjectName("profilePass")
        self.verticalLayout.addWidget(self.profilePass)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setSpacing(10)
        self.hboxlayout.setObjectName("hboxlayout")
        self.vboxlayout = QtGui.QVBoxLayout()
        self.vboxlayout.setObjectName("vboxlayout")
        self.syncLabel = QtGui.QLabel(self.tab_2)
        self.syncLabel.setWordWrap(True)
        self.syncLabel.setOpenExternalLinks(True)
        self.syncLabel.setObjectName("syncLabel")
        self.vboxlayout.addWidget(self.syncLabel)
        self.syncMedia = QtGui.QCheckBox(self.tab_2)
        self.syncMedia.setObjectName("syncMedia")
        self.vboxlayout.addWidget(self.syncMedia)
        self.syncOnProgramOpen = QtGui.QCheckBox(self.tab_2)
        self.syncOnProgramOpen.setObjectName("syncOnProgramOpen")
        self.vboxlayout.addWidget(self.syncOnProgramOpen)
        self.fullSync = QtGui.QCheckBox(self.tab_2)
        self.fullSync.setObjectName("fullSync")
        self.vboxlayout.addWidget(self.fullSync)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.syncDeauth = QtGui.QPushButton(self.tab_2)
        self.syncDeauth.setAutoDefault(False)
        self.syncDeauth.setObjectName("syncDeauth")
        self.horizontalLayout.addWidget(self.syncDeauth)
        spacerItem1 = QtGui.QSpacerItem(40, 1, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.vboxlayout.addLayout(self.horizontalLayout)
        self.hboxlayout.addLayout(self.vboxlayout)
        self.verticalLayout_4.addLayout(self.hboxlayout)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_9 = QtGui.QLabel(self.tab)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_3.addWidget(self.label_9)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_10 = QtGui.QLabel(self.tab)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 1)
        self.numBackups = QtGui.QSpinBox(self.tab)
        self.numBackups.setMinimumSize(QtCore.QSize(60, 0))
        self.numBackups.setMaximumSize(QtCore.QSize(60, 16777215))
        self.numBackups.setObjectName("numBackups")
        self.gridLayout_2.addWidget(self.numBackups, 0, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.tab)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 2, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 0, 3, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.openBackupFolder = QtGui.QLabel(self.tab)
        self.openBackupFolder.setObjectName("openBackupFolder")
        self.verticalLayout_3.addWidget(self.openBackupFolder)
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        spacerItem4 = QtGui.QSpacerItem(20, 59, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.label_21 = QtGui.QLabel(self.tab)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_3.addWidget(self.label_21)
        self.tabWidget.addTab(self.tab, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(Preferences)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Help)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(Preferences)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Preferences.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Preferences.reject)
        QtCore.QMetaObject.connectSlotsByName(Preferences)
        Preferences.setTabOrder(self.showEstimates, self.showProgress)
        Preferences.setTabOrder(self.showProgress, self.stripHTML)
        Preferences.setTabOrder(self.stripHTML, self.pastePNG)
        Preferences.setTabOrder(self.pastePNG, self.useCurrent)
        Preferences.setTabOrder(self.useCurrent, self.newSpread)
        Preferences.setTabOrder(self.newSpread, self.dayOffset)
        Preferences.setTabOrder(self.dayOffset, self.lrnCutoff)
        Preferences.setTabOrder(self.lrnCutoff, self.timeLimit)
        Preferences.setTabOrder(self.timeLimit, self.profilePass)
        Preferences.setTabOrder(self.profilePass, self.syncMedia)
        Preferences.setTabOrder(self.syncMedia, self.syncOnProgramOpen)
        Preferences.setTabOrder(self.syncOnProgramOpen, self.syncDeauth)
        Preferences.setTabOrder(self.syncDeauth, self.numBackups)
        Preferences.setTabOrder(self.numBackups, self.buttonBox)
        Preferences.setTabOrder(self.buttonBox, self.tabWidget)

    def retranslateUi(self, Preferences):
        Preferences.setWindowTitle(_("Preferences"))
        self.showEstimates.setText(_("Show next review time above answer buttons"))
        self.showProgress.setText(_("Show remaining card count during review"))
        self.stripHTML.setText(_("Strip HTML when pasting text"))
        self.pastePNG.setText(_("Paste clipboard images as PNG"))
        self.useCurrent.setItemText(0, _("When adding, default to current deck"))
        self.useCurrent.setItemText(1, _("Change deck depending on note type"))
        self.label_23.setText(_("Next day starts at"))
        self.label_24.setText(_("Learn ahead limit"))
        self.label_29.setText(_("mins"))
        self.label_30.setText(_("Timebox time limit"))
        self.label_39.setText(_("mins"))
        self.label_40.setText(_("hours past midnight"))
        self.profilePass.setText(_("Profile Password..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _("Basic"))
        self.syncLabel.setText(_("<b>Synchronisation</b>"))
        self.syncMedia.setText(_("Synchronize audio and images too"))
        self.syncOnProgramOpen.setText(_("Automatically sync on profile open/close"))
        self.fullSync.setText(_("On next sync, force changes in one direction"))
        self.syncDeauth.setText(_("Deauthorize"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _("Network"))
        self.label_9.setText(_("<b>Backups</b><br>Anki will create a backup of your collection each time it is closed or synchronized."))
        self.label_10.setText(_("Keep"))
        self.label_11.setText(_("backups"))
        self.openBackupFolder.setText(_("<a href=\"backups\">Open backup folder</a>"))
        self.label_4.setText(_("Note: Media is not backed up. Please create a periodic backup of your Anki folder to be safe."))
        self.label_21.setText(_("Some settings will take effect after you restart Anki."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _("Backups"))

